spring.application.name=demo
server.port=8085

# In-Memory Configuration (Data is lost on restart)
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true

spring.web.error.include-message=always
